name             'the_commons'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures the_commons'
long_description 'Installs/Configures the_commons'
version          '0.1.0'
