name 'cooking'
maintainer 'The Authors'
maintainer_email 'yrros@hotmail.com'
license 'all_rights'
description 'Installs/Configures learn_chef_redis'
long_description 'Installs/Configures learn_chef_redis'
version '0.1.0'
